services:
  postgres:
    image: postgres:15
    container_name: postgres_ex20
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exercise20db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_ex20
    restart: unless-stopped
    ports:
      - "8081:8080"

  redis:
    image: redis
    container_name: redis_ex20
    restart: unless-stopped
    ports:
      - "6379:6379"
